// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
const awsmobile = {
  Auth: {
    mandatorySignIn: true,
    // Amazon Cognito Region
    region: 'us-east-1',
    //Amazon Cognito User Pool ID
    userPoolId: 'us-east-1_0fIbiKHAY',
    //Amazon Cognito Web Client ID (26-char alphanumeric string)
    userPoolWebClientId: 'ts2d0dsgphtpjjv2qpkc2t1e9',
  },
  aws_appsync_graphqlEndpoint:
    'https://3ys7qk6psng2jcxok4jm66bevm.appsync-api.us-east-1.amazonaws.com/graphql',
  aws_appsync_region: 'us-east-1',
  aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
};
export default awsmobile;
